package harness

import (
	"fmt"
	"strings"
)

const placeholderBanner = "> **PLACEHOLDER** — Generated by `shipwright scaffold`. Fill in with real content before approval."

type TemplateData struct {
	ProjectName    string
	ProjectID      string
	InitialRequest string
	CurrentPhase   string
	RequiresUI     *bool
	HasAPI         *bool
}

func TemplateDataFromState(s *State) TemplateData {
	return TemplateData{
		ProjectName:    s.ProjectName,
		ProjectID:      s.ProjectID,
		InitialRequest: s.InitialRequest,
		CurrentPhase:   s.CurrentPhase,
		RequiresUI:     s.RequiresUI,
	}
}

func GenerateArtifact(path string, data TemplateData) (string, error) {
	generators := map[string]func(TemplateData) string{
		"product/context.md":                  genProductContext,
		"product/assumptions.md":              genProductAssumptions,
		"product/open-questions.md":           genProductOpenQuestions,
		"product/scope.md":                    genProductScope,
		"architecture/technology-options.md":  genTechOptions,
		"architecture/system-architecture.md": genSystemArchitecture,
		"project/project-charter.md":          genProjectCharter,
		"project/project-plan.md":             genProjectPlan,
		"project/risk-register.md":            genRiskRegister,
		"project/delivery-plan.md":            genDeliveryPlan,
		"project/change-management.md":        genChangeManagement,
		"project/acceptance-report.md":        genAcceptanceReport,
		"contracts/openapi.yaml":              genOpenAPI,
		"backlog/epics.md":                    genEpics,
		"backlog/user-stories.md":             genUserStories,
		"backlog/frontend-tasks.md":           genFrontendTasksPlaceholder,
		"backlog/backend-tasks.md":            genBackendTasksPlaceholder,
		"sdd/proposal.md":                     genSDDProposal,
		"sdd/spec.md":                         genSDDSpec,
		"sdd/tasks.md":                        genSDDTasks,
		"progress/frontend.md":                genFrontendProgress,
		"progress/backend.md":                 genBackendProgress,
		"reports/contract-test-report.md":     genContractTestReport,
		"reports/qa-report.md":                genQAReport,
		"reports/security-review.md":          genSecurityReview,
		"reports/review-checklist.md":         genReviewChecklist,
	}

	gen, ok := generators[path]
	if !ok {
		return "", fmt.Errorf("no template for: %s", path)
	}
	return gen(data), nil
}

func ph(data TemplateData) string {
	var sb strings.Builder
	sb.WriteString(placeholderBanner)
	sb.WriteString("\n\n")
	return sb.String()
}

func reqStr(data TemplateData) string {
	if data.InitialRequest == "" {
		return "(not set)"
	}
	return data.InitialRequest
}

func genProductContext(d TemplateData) string {
	return fmt.Sprintf(`# Product Context

%s

## Project

%s

## User request

%s

## Problem statement

(pending — describe the problem this product solves)

## Target users

(pending — who are the users?)

## Business context

(pending — what business need does this address?)

## Constraints

(pending — regulatory, technical, budget, timeline)
`, ph(d), d.ProjectName, reqStr(d))
}

func genProductAssumptions(d TemplateData) string {
	return fmt.Sprintf(`# Assumptions

%s

## Project: %s

## Assumptions

1. (pending — list assumptions made during discovery)

## Validated

(none yet)

## Invalidated

(none yet)
`, ph(d), d.ProjectName)
}

func genProductOpenQuestions(d TemplateData) string {
	return fmt.Sprintf(`# Open Questions

%s

## Project: %s

## Critical (block scope approval)

(pending — list critical questions that must be answered before scope approval)

## Non-critical

(pending — questions that can be resolved later)

## Resolved

(none yet)
`, ph(d), d.ProjectName)
}

func genProductScope(d TemplateData) string {
	return fmt.Sprintf(`# Product Scope

%s

## Project: %s

## In scope

(pending — what is included in this delivery)

## Out of scope

(pending — what is explicitly excluded)

## Success criteria

(pending — how do we know it's done?)

## Key features

(pending — list the key features to deliver)

## Non-functional requirements

(pending — performance, security, accessibility, etc.)
`, ph(d), d.ProjectName)
}

func genTechOptions(d TemplateData) string {
	return fmt.Sprintf(`# Technology Options

%s

## Project: %s

## Option A

- **Stack:** (pending)
- **Pros:** (pending)
- **Cons:** (pending)
- **Risks:** (pending)

## Option B

- **Stack:** (pending)
- **Pros:** (pending)
- **Cons:** (pending)
- **Risks:** (pending)

## Recommendation

(pending — which option and why)
`, ph(d), d.ProjectName)
}

func genSystemArchitecture(d TemplateData) string {
	return fmt.Sprintf(`# System Architecture

%s

## Project: %s

## Overview

(pending — high-level architecture description)

## Components

(pending — list components and their responsibilities)

## Data flow

(pending — how data moves through the system)

## Technology stack

(pending — confirmed technology choices)

## Deployment

(pending — deployment topology)

## Security model

(pending — authentication, authorization, data protection)
`, ph(d), d.ProjectName)
}

func genProjectCharter(d TemplateData) string {
	return fmt.Sprintf(`# Project Charter

%s

## Project: %s

## Vision

(pending — one sentence describing the project vision)

## Objectives

(pending — measurable objectives)

## Scope summary

(pending — brief scope summary, reference product/scope.md)

## Stakeholders

(pending — list key stakeholders and roles)

## Success criteria

(pending — how is success measured?)

## Budget/Resources

(pending — team size, budget, timeline constraints)

## Sponsor

(pending — who is the project sponsor?)
`, ph(d), d.ProjectName)
}

func genProjectPlan(d TemplateData) string {
	return fmt.Sprintf(`# Project Plan

%s

## Project: %s

## Phases

| Phase | Estimated duration | Status |
|---|---|---|
| Discovery | (pending) | (pending) |
| Planning | (pending) | (pending) |
| Design | (pending) | (pending) |
| Implementation | (pending) | (pending) |
| QA | (pending) | (pending) |
| Acceptance | (pending) | (pending) |

## Milestones

(pending — list key milestones)

## Dependencies

(pending — list dependencies between phases/teams)

## Communication plan

(pending — how often, what format, to whom)
`, ph(d), d.ProjectName)
}

func genRiskRegister(d TemplateData) string {
	return fmt.Sprintf(`# Risk Register

%s

## Project: %s

| # | Risk | Impact | Probability | Mitigation | Status |
|---|------|--------|-------------|------------|--------|
| 1 | (pending) | (pending) | (pending) | (pending) | open |
`, ph(d), d.ProjectName)
}

func genDeliveryPlan(d TemplateData) string {
	return fmt.Sprintf(`# Delivery Plan

%s

## Project: %s

## Delivery approach

(pending — describe how the product will be delivered)

## UI requirement

(pending — does this project require UI design? Set requires_ui in state.json)

## Team allocation

(pending — who works on what)

## Delivery milestones

(pending — list delivery milestones with dates)
`, ph(d), d.ProjectName)
}

func genChangeManagement(d TemplateData) string {
	return fmt.Sprintf(`# Change Management

%s

## Project: %s

## Active change requests

(pending — reference any CR files in project/change-requests/)

## Change process

1. User requests change via `+"`shipwright request-change`"+`
2. CR file created in project/change-requests/
3. Impact assessment completed
4. Decision: approved / rejected / postponed
5. If approved, scope/backlog updated and phase adjusted

## Impact assessment

(pending — describe impact of current change request)
`, ph(d), d.ProjectName)
}

func genAcceptanceReport(d TemplateData) string {
	return fmt.Sprintf(`# Acceptance Report

%s

## Project: %s

## Deliverables

(pending — list what was delivered)

## Acceptance criteria met

(pending — reference success criteria from product/scope.md)

## Known issues

(pending — list known issues or limitations)

## User acceptance

- [ ] User accepts delivery
- [ ] User requests changes (use shipwright request-change)

## Sign-off

- **Accepted by:** (pending)
- **Date:** (pending)
`, ph(d), d.ProjectName)
}

func genOpenAPI(d TemplateData) string {
	return fmt.Sprintf(`openapi: 3.0.3
# %s — PLACEHOLDER generated by shipwright scaffold
# Fill in with real API specification.
# Remove this file if the project has no API.
info:
  title: %s API
  version: 0.1.0
  description: |
    (pending — describe the API)
paths:
  # (pending — define API endpoints)
  # /example:
  #   get:
  #     summary: Example endpoint
  #     responses:
  #       '200':
  #         description: Success
components:
  # (pending — define schemas, security schemes, etc.)
`, d.ProjectName, d.ProjectName)
}

func genEpics(d TemplateData) string {
	return fmt.Sprintf(`# Epics

%s

## Project: %s

## Epic 1: (pending)

**Description:** (pending)

**User stories:** (reference backlog/user-stories.md)

## Epic 2: (pending)

**Description:** (pending)

**User stories:** (reference backlog/user-stories.md)
`, ph(d), d.ProjectName)
}

func genUserStories(d TemplateData) string {
	return fmt.Sprintf(`# User Stories

%s

## Project: %s

## US-001

**As a** (pending)
**I want** (pending)
**So that** (pending)

**Acceptance criteria:**
- (pending)

## US-002

**As a** (pending)
**I want** (pending)
**So that** (pending)

**Acceptance criteria:**
- (pending)
`, ph(d), d.ProjectName)
}

func genSDDProposal(d TemplateData) string {
	return fmt.Sprintf(`# SDD Proposal

%s

## Change name

%s

## Intent

(pending — what is being built and why)

## Scope

(pending — reference product/scope.md)

## Target users

(pending — reference product/context.md)

## Main scenario

(pending — describe the main usage scenario)

## Success criteria

(pending — reference product/scope.md success criteria)

## Risks

(pending — reference project/risk-register.md)
`, ph(d), d.ProjectID)
}

func genSDDSpec(d TemplateData) string {
	return fmt.Sprintf(`# SDD Spec

%s

## Project: %s

## Requirements

(pending — functional and non-functional requirements)

## Scenarios

(pending — describe key scenarios with Given/When/Then)

## Constraints

(pending — technical constraints)

## Out of scope

(pending — what is explicitly excluded)
`, ph(d), d.ProjectName)
}

func genSDDTasks(d TemplateData) string {
	return fmt.Sprintf(`# SDD Tasks

%s

## Project: %s

## Implementation tasks

- [ ] (pending — task 1)
- [ ] (pending — task 2)
- [ ] (pending — task 3)

## Frontend tasks

- [ ] (pending — FE task 1)

## Backend tasks

- [ ] (pending — BE task 1)

## QA tasks

- [ ] (pending — QA task 1)

## Done criteria

- All tasks completed
- Tests passing
- Code reviewed
- Documentation updated
`, ph(d), d.ProjectName)
}

func genFrontendProgress(d TemplateData) string {
	return fmt.Sprintf(`# Frontend Progress

%s

## Project: %s

## Status: PLACEHOLDER

> This is a placeholder. No real frontend implementation has been done.
> Replace with actual progress when implementation runs.

## Completed

(none — placeholder)

## In progress

(none — placeholder)

## Blocked

(none — placeholder)

## Evidence

(none — placeholder)
`, ph(d), d.ProjectName)
}

func genBackendProgress(d TemplateData) string {
	return fmt.Sprintf(`# Backend Progress

%s

## Project: %s

## Status: PLACEHOLDER

> This is a placeholder. No real backend implementation has been done.
> Replace with actual progress when implementation runs.

## Completed

(none — placeholder)

## In progress

(none — placeholder)

## Blocked

(none — placeholder)

## Evidence

(none — placeholder)
`, ph(d), d.ProjectName)
}

func genContractTestReport(d TemplateData) string {
	return fmt.Sprintf(`# Contract Test Report

%s

## Project: %s

## Status: PLACEHOLDER

> This is a placeholder. No real contract tests have been run.
> Replace with actual test results when implementation runs.

## Contract evidence:

(pending — command output, coverage, or verification notes)

## Results

(none — placeholder)

## Contract coverage

(none — placeholder)

## Issues found

(none — placeholder)
`, ph(d), d.ProjectName)
}

func genQAReport(d TemplateData) string {
	return fmt.Sprintf(`# QA Report

%s

## Project: %s

## Status: PLACEHOLDER

> This is a placeholder. No real QA testing has been done.
> Replace with actual test results when implementation runs.

## Test evidence:

(pending — commands run, manual test notes, screenshots, or automated test output)

## Test summary

(none — placeholder)

## Test coverage

(none — placeholder)

## Issues found

Use this format:

- LOW: description
- MEDIUM: description — Decision: accepted/deferred/mitigated
- CRITICAL: description

## Recommendation

(pending — pass / fail / conditional pass)
`, ph(d), d.ProjectName)
}

func genSecurityReview(d TemplateData) string {
	return fmt.Sprintf(`# Security Review

%s

## Project: %s

## Status: PLACEHOLDER

> This is a placeholder. No real security review has been done.
> Replace with actual review when implementation runs.

## Security evidence:

(pending — checks performed, files reviewed, auth/data/input validation evidence)

## Findings

Use this format:

- LOW: description
- MEDIUM: description — Decision: accepted/deferred/mitigated
- CRITICAL: description

## Risk assessment

(pending — low / medium / high)

## Recommendations

(pending — list security improvements)
`, ph(d), d.ProjectName)
}

func genReviewChecklist(d TemplateData) string {
	return fmt.Sprintf(`# Review Checklist

%s

## Project: %s

## Evidence gate

- [ ] reports/contract-test-report.md includes Contract evidence
- [ ] reports/qa-report.md includes Test evidence
- [ ] reports/security-review.md includes Security evidence
- [ ] No report is still placeholder-only

## Finding policy

- [ ] CRITICAL findings: none open
- [ ] MEDIUM findings: each has explicit decision
- [ ] LOW findings: recorded and accepted for later tracking

## Contract-first checks

- [ ] Frontend keeps mock mode
- [ ] Frontend keeps HTTP/real API mode
- [ ] Backend documents consistent error response format
- [ ] Contract mismatches are reported as CRITICAL

## Final review recommendation

- [ ] PASS — ready for Technical Lead review
- [ ] CONDITIONAL PASS — only LOW findings remain
- [ ] FAIL — CRITICAL findings or undecided MEDIUM findings remain
`, ph(d), d.ProjectName)
}

func genFrontendTasksPlaceholder(d TemplateData) string {
	return fmt.Sprintf(`# Frontend Tasks

%s

## Project: %s

> **PLACEHOLDER** — This file will be generated from contracts/openapi.yaml.
> Run: shipwright contract generate-tasks
> Or if the Technical Lead agent is active, it will generate this from the contract.

## Contract-First Rules

- All tasks MUST reference endpoints from contracts/openapi.yaml
- Mock mode is MANDATORY — every data-fetching task must have mock + HTTP mode
- Mocks MUST derive from contract response schemas
- HTTP adapter MUST be separate from mock adapter
- NEVER delete mocks — mock mode must coexist with real API mode
- NEVER invent endpoints not in the contract

## Task List

(pending — run: shipwright contract generate-tasks)
`, ph(d), d.ProjectName)
}

func genBackendTasksPlaceholder(d TemplateData) string {
	return fmt.Sprintf(`# Backend Tasks

%s

## Project: %s

> **PLACEHOLDER** — This file will be generated from contracts/openapi.yaml.
> Run: shipwright contract generate-tasks
> Or if the Technical Lead agent is active, it will generate this from the contract.

## Contract-First Rules

- All tasks MUST implement endpoints from contracts/openapi.yaml EXACTLY
- API MUST match contract: path, method, request schema, response schema
- Error responses MUST match contract format (400, 401, 500 minimum)
- NEVER break the contract without a change request
- If the contract is wrong, STOP and request a change request
- Every endpoint MUST have consistent error responses
- Every endpoint MUST have tests (domain + API)

## Task List

(pending — run: shipwright contract generate-tasks)
`, ph(d), d.ProjectName)
}
